### ISSUE TITLE
Predict command

### ISSUE THREAD

**Issue by Raprodent** [craigmacartney/Wave-U-Net-For-Speech-Enhancement#1]
Hey, is this repo only for certain audio files or is it an improvement of the Wave-U-Net?
Sorry for being a noob. Merry XMAS!

**Comment by craigmacartney** [comment]
Hi there, it is an implementation of the Wave-U-Net for a speech enhancement task and, in my experiments, the network has been adapted in terms of depth (layer size) and width (filter size).

However, presuming the data is structured to facilitate the data loader in loading clean, noise and mixture audio then, with minimal alterations, the code could be adapted to be generalised to being implemented for any audio source separation problem. Although for training, it would be advisable to adapt the network size, depending on the task.
