### ISSUE TITLE
Unsure about how to load the data

### ISSUE THREAD

**Issue by MathewSam** [craigmacartney/Wave-U-Net-For-Speech-Enhancement#3]
Could you elaborate on the data preparation? Sorry for being a noob

**Comment by guozixunnicolas** [comment]
i prepared my own and it works now. simply just download clean speech and noise and mix them together.

**Comment by MathewSam** [comment]
Yeah I made my own version where I created my own data loader

**Comment by roOokie-jiang** [comment]
> i prepared my own and it works now. simply just download clean speech and noise and mix them together.

can your show me detail of this file? Thanks
