### ISSUE TITLE
XML file

### ISSUE THREAD

**Issue by guozixunnicolas** [craigmacartney/Wave-U-Net-For-Speech-Enhancement#5]
Hello,

Could you share some insights on how to prepare the xml file?

Thanks!

**Comment by guozixunnicolas** [comment]
Closed the issue. Solve by reading file from txt

**Comment by roOokie-jiang** [comment]
Can you show me about the xml file or your txt, I don't know the data structure of this file, so I don't know how to make a txt file. Waiting for your replay. My E-mail: sjiang@mori.m.is.nagoya-u.ac.jp
