### ISSUE TITLE
reverbation

### ISSUE THREAD

**Issue by guozixunnicolas** [craigmacartney/Wave-U-Net-For-Speech-Enhancement#6]
Hello,

I have trained the de-noising model on my own and it works perfect.

In the paper there's a part saying the model can also deal with reverberated audio.

May I know how can this be done since this script only focuses on noisy data? I am curious what will the output be if we feed reverberant audio, it will be separated only to audio or audio+something else? It will be great if you also provide some information on preparing reverberant dataset:)

Best,

ZX

**Comment by roOokie-jiang** [comment]
May I get your XML file detail or txt? I have no idea about this part. Sorry for noob me.

**Comment by guozixunnicolas** [comment]
import os.path

from Sample import Sample
import Metadata
from lxml import etree

def create_sample(path):
    sr, channels, duration = Metadata.get_audio_metadata(path)
    #print(path,sr,channels,duration)
    return Sample(path,sr,channels,duration)


def getAudioData(file_path):
    samples=list()
    with open (file_path,'r') as f_path:
        for name in f_path:
            mix_path=name.split(' ')[0]        
            noise_path=name.split(' ')[1]
            speech_path=name.split(' ')[2][0:-1]
            #print(name)
            try:
                mix=create_sample(mix_path)
                noise=create_sample(noise_path)
                speech=create_sample(speech_path)
                samples.append((mix,noise,speech))
            except:
                print('error in ',name)
    return samples
if __name__=='__main__':
    getAudioData('list.txt')

**Comment by guozixunnicolas** [comment]
@roOokie-jiang I modify the script like this:)

**Comment by roOokie-jiang** [comment]
Thanks for your reply. What's your txt? @zguo008

**Comment by guozixunnicolas** [comment]
@roOokie-jiang simply mix1 noise1 speech1 (next line) mix2 noise2 speech2
